ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bmosRoleKeys" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bmosPermissions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bmosIsSuperAdmin" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "WorkSession" ADD COLUMN IF NOT EXISTS "externalTaskId" TEXT;

ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "externalId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "parentExternalId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "parentTitle" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "projectExternalId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "projectName" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "clientExternalId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "clientName" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Task_externalId_key" ON "Task"("externalId");
